mv -i "Hulk.mp4" "Hulk.(2003).mp4"
mv -i "Mission Impossible II.mp4" "Mission.Impossible.II.(2000).mp4"
mv -i "Mission To Mars.mp4" "Mission.To.Mars.(2000).mp4"
mv -i "Monsters, Inc .mp4" "Monsters,.Inc..(2001).mp4"
mv -i "Mr & Mrs Smith.mp4" "Mr..&.Mrs..Smith.(2005).mp4"
mv -i "Saving Private Ryan.mp4" "Saving.Private.Ryan.(1998).mp4"
mv -i "Scrooged.mp4" "Scrooged.(1988).mp4"
mv -i "Shrek.mp4" "Shrek.(2001).mp4"
mv -i "Sinbad And The Eye Of The Tiger.mp4" "Sinbad.And.The.Eye.Of.The.Tiger.(1977).mp4"
mv -i "Sky Captain And The World Of Tomorrow.mp4" "Sky.Captain.And.The.World.Of.Tomorrow.(2004).mp4"
mv -i "Spiderman 2 mp4" "Spiderman 2.mp4"
mv -i "Spiderman mp4" "Spiderman.mp4"
mv -i "Spiderman3 mp4" "Spiderman3.mp4"
mv -i "xXx.mp4" "xXx.(2002).mp4"
