#
# Title:        Makefile
# Project:	Scripts
# Desc:
# 
#   
# 
# Notes:
# 
# Author:	Paul A. Houghton - (paul.houghton@wcom.com)
# Created:	06/22/99 06:32
#
# Revision History: (See end of file for Revision Log)
#
#   Last Mod By:    $Author$
#   Last Mod:	    $Date$
#   Version:	    $Revision$
#
#   $Id$
# 



install:
	$(MAKE) -C ../home install


#
# $Log$
# Revision 1.1  2003/05/18 23:47:02  houghton
# *** empty log message ***
#
#

# Local Variables:
# mode:makefile
# End:
