mv -i "Hulk.(2003).mp4" "Hulk.mp4"
mv -i "Mission.Impossible.II.(2000).mp4" "Mission Impossible II.mp4"
mv -i "Mission.To.Mars.(2000).mp4" "Mission To Mars.mp4"
mv -i "Monsters,.Inc..(2001).mp4" "Monsters, Inc .mp4"
mv -i "Mr..&.Mrs..Smith.(2005).mp4" "Mr & Mrs Smith.mp4"
mv -i "Saving.Private.Ryan.(1998).mp4" "Saving Private Ryan.mp4"
mv -i "Scrooged.(1988).mp4" "Scrooged.mp4"
mv -i "Shrek.(2001).mp4" "Shrek.mp4"
mv -i "Sinbad.And.The.Eye.Of.The.Tiger.(1977).mp4" "Sinbad And The Eye Of The Tiger.mp4"
mv -i "Sky.Captain.And.The.World.Of.Tomorrow.(2004).mp4" "Sky Captain And The World Of Tomorrow.mp4"
mv -i "Spiderman 2.mp4" "Spiderman 2 mp4"
mv -i "Spiderman.mp4" "Spiderman mp4"
mv -i "Spiderman3.mp4" "Spiderman3 mp4"
mv -i "xXx.(2002).mp4" "xXx.mp4"
