mv -i Mix_Wallpaper_10/flameplasticxmbfilteredbx8.JPG Mix_Wallpaper_10_flameplasticxmbfilteredbx8.JPG
mv -i Mix_Wallpaper_11/mario.JPG Mix_Wallpaper_11_mario.JPG
mv -i Mix_Wallpaper_9/bmw_m6.JPG Mix_Wallpaper_9_bmw_m6.JPG
mv -i background/nature_wallpaper_pack/1.JPG background_nature_wallpaper_pack_1.JPG
mv -i background/nature_wallpaper_pack/10.JPG background_nature_wallpaper_pack_10.JPG
mv -i background/nature_wallpaper_pack/2.JPG background_nature_wallpaper_pack_2.JPG
mv -i background/nature_wallpaper_pack/3.JPG background_nature_wallpaper_pack_3.JPG
mv -i background/nature_wallpaper_pack/4.JPG background_nature_wallpaper_pack_4.JPG
mv -i background/nature_wallpaper_pack/5.JPG background_nature_wallpaper_pack_5.JPG
mv -i background/nature_wallpaper_pack/6.JPG background_nature_wallpaper_pack_6.JPG
mv -i background/nature_wallpaper_pack/7.JPG background_nature_wallpaper_pack_7.JPG
mv -i background/nature_wallpaper_pack/8.JPG background_nature_wallpaper_pack_8.JPG
mv -i background/nature_wallpaper_pack/9.JPG background_nature_wallpaper_pack_9.JPG
mv -i background/wpk_Non-Widescreen_Watren.JPG background_wpk_Non-Widescreen_Watren.JPG
